version: '3.8'

services:
  mysql-main:
    image: mysql:8.4.3
    container_name: fineapple-main
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fineapple
    ports:
      - "3307:3306"
    volumes:
      - mysql_main_data:/var/lib/mysql

volumes:
  mysql_main_data:
